enableGitInfo: true
enableRobotsTXT: true
sitemap:
 - changefreq = "monthly"
 - filename = "sitemap.xml"
 - priority = 0.5
blackfriday:
 angledQuotes: true
 extensionsmask:
 - autolink: false
 hrefTargetBlank: true
 plainIDAnchors: true
