baseURL = "/"
languageCode = "en-us"
title = "Demo Site with Hugo"
theme = "kube"
description = "Demo Site is built with Hugo using the kube theme."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "F5Networks" # add your company name
  github = "jputrino" # add your github profile name
  twitter = "" # add your twitter profile
  email = "myname@myaddress.com"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"

[Params.seo.webmaster_verifications]
  google = "" # Optional, Google verification code
  bing = "" # Optional, Bing verification code
  alexa = "" # Optional, Alexa verification code
  yandex = "" # Optional, Yandex verification code